import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Manrope } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { NavBar } from "../components/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const arial = localFont({
  src: "./fonts/Arial.ttf",
  variable: "--font-arial",
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(arial.className, inter.variable, "antialiased")}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
